[auth]
provider = "r2r"
access_token_lifetime_in_minutes = 60
refresh_token_lifetime_in_days = 7
require_authentication = false
require_email_verification = false
default_admin_email = "admin@example.com"
default_admin_password = "change_me_immediately"

[chunking]
provider = "r2r"
method = "recursive"
chunk_size = 512
chunk_overlap = 50

[completion]
provider = "litellm"
concurrent_request_limit = 1

  [completion.generation_config]
  model = "anthropic/claude-3-opus-20240229"
  
[crypto]
provider = "bcrypt"

[database]
provider = "postgres"

[embedding]
provider = "litellm"
base_model = "embed-english-v3.0"
base_dimension = 1024
batch_size = 32
add_title_as_prefix = true

[eval]
provider = "None"

[kg]
provider = "None"

[logging]
provider = "local"
log_table = "logs"
log_info_table = "log_info"

[parsing]
provider = "r2r"
excluded_parsers = ["mp4"]

[prompt]
provider = "r2r"

[agent]
system_instruction_name = "rag_agent"
tool_names = ["search"]